### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by bNobo** [bNobo/needabreak#12]
I've made the actual logo representing a coffee cup in 5 minutes with Paint 3D. This application certainly deserve a better logo :)

**Comment by kourosh95** [comment]
I created a flat design vector graphic of a coffee mug with inkscape. I've attached both svg and png files. vector can be found here: https://www.dropbox.com/s/wpl1ici6tk5tgwh/coffee.svg?dl=0
![g1060](https://user-images.githubusercontent.com/39087600/78328734-93667e00-75cb-11ea-8da1-d9baaa8b18e7.png)

**Comment by bNobo** [comment]
Hi @kourosh95 ! Thank you, it looks very nice ! I will integrate it soon.

**Comment by bNobo** [comment]
I've created a branch "new-logo" to test your icon an it looks great !

In taskbar :
![taskbar](https://1adhja.db.files.1drv.com/y4m0OkzbTHioQn68dul-mxehiNfRTcDusaTgQhUTmnixEjwV-ZV2nnZy_CoplpnABUgjF93Lq-b0CAf0F2vrwvKFecl2yzoOZtsX_JJmlMxMwkg4r7t1HafMPRdtzzUDyAP4f5ran8H0mDCrbhZlELfj0mPMxPuXex6EkiyzCvbFtFcZod6MCUhmOgXYFO6qeqmPOXFb-l-3J-FTl13RIqRig?width=873&height=201&cropmode=none)

In file explorer :
![fileexplorer](https://oiw6gg.db.files.1drv.com/y4mNcrqwc9s87UV2WSPjsbNv8yuiBuW87any02Qf5QPXvZrzsv-2W15rhBGcy8jRwttbwqBpCHllM4Owk822uY-OuMdW3HYPRRDQZJyhWsQ7-UjVANXaVXqiIzx0Q6Ofswuvmep68lBK1pSc6Z9DXfmWpsOsoz_byoUzrjv7YVDYFbZl4Q4k6nsGJltG1ri3YnODv_C6gtI90R50Zto_i9R-A?width=546&height=327&cropmode=none)

**Comment by kourosh95** [comment]
Glad you liked it! :)
