### ISSUE TITLE
Review english translations

### ISSUE THREAD

**Issue by bNobo** [bNobo/needabreak#2]
Application was first developed in french and I have used bing translator to make an english version. I have reviewed translations but i'm not native english speaking so it would be great if someone native could verify translations.

**Comment by Armdt** [comment]
Hi, I'm not native but I'd like to help

**Comment by Armdt** [comment]
hi @bNobo  I'm not native but I'd like to help

**Comment by Armdt** [comment]
hi @bNobo  I'm not native but I'd like to help, Can I work on this?

**Comment by bNobo** [comment]
hi @Armdt, I sent you an invitation a minute ago, now you should be able to contribute :) Don't forget to create a new branch because you won't be allowed to push directly into master.
