### ISSUE TITLE
Use squirrel for installation and updates

### ISSUE THREAD

**Issue by bNobo** [bNobo/needabreak#34]
**Is your feature request related to a problem? Please describe.**
* ClickOnce requires a web site to store binaries ~and a certificate to sign the installer~. Currently binaries are stored on GitHub Pages which is quite slow (several seconds to download only 2Mb!). 
* ~A certificate is expansive so given that it is an open source application with no revenue there is currently no certificate. Final users get a red warning from the UAC each time they download or install the application~
* When there is an update the user has to wait until its installation after having launched the application

**Describe the solution you'd like**

Create a package nuget from the project and deploy it using [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows)

**Describe alternatives you've considered**

I've considered many alternatives in issue #6 but none of these seem to come close to what Squirrel offers.

**Additional context**

![squirrel.windows](https://user-images.githubusercontent.com/11414291/84153662-72f0ef00-aa66-11ea-8a9e-2ae7c4ed4a99.png)

[Getting Started Guide](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/0-overview.md)

**Comment by bNobo** [comment]
[Squirrel.Windows is no longer maintained](https://github.com/electron/electron/issues/17722)

**Comment by caesay** [comment]
Hi there, Just ran into this from the linked electron issue. Thought I would drop a note as I [maintain a popular Squirrel fork](https://github.com/clowd/Clowd.Squirrel) that has fixed a lot of the issues from the original project!
