### ISSUE TITLE
Add a "lock now !" button on the main window (count down)

### ISSUE THREAD

**Issue by bNobo** [bNobo/needabreak#4]
Sometimes when the countdown before locking appears there is nothing to save and we just want to lock the screen and leave our seat. Actually we have to wait for the countdown to reach 0 or manually lock the screen using "windows + L". It would be easier if they were a "lock now !" button on the countdown window

**Comment by Armdt** [comment]
Hey @bNobo  when i try to open MainWindows.xaml I get an Error that says 
"The resource "{x:Type TextBlock}" could not be resolved, Do you have any idea why?
